export const articleConstants = {
    ARTICLES_REQUEST: 'ARTICLES_REQUEST',
    ARTICLES_SUCCESS: 'ARTICLES_SUCCESS',
    ARTICLES_FAILURE: 'ARTICLES_FAILURE',

    ARTICLE_REQUEST: 'ARTICLE_REQUEST',
    ARTICLE_SUCCESS: 'ARTICLE_SUCCESS',
    ARTICLE_FAILURE: 'ARTICLE_FAILURE',

    DELETE_ARTICLE_REQUEST: 'DELETE_ARTICLE_REQUEST',
    DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
    DELETE_ARTICLE_FAILURE: 'DELETE_ARTICLE_FAILURE',

    CREATE_ARTICLE_REQUEST: 'CREATE_ARTICLE_REQUEST',
    CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_FAILURE: 'CREATE_ARTICLE_FAILURE',

    UPDATE_ARTICLE_PARAGRAPH: 'UPDATE_ARTICLE_PARAGRAPH'
}