export const suggestionConstants = {
    GET_SUGGESTIONS_REQUEST: 'GET_SUGGESTIONS_REQUEST',
    GET_SUGGESTIONS_SUCCESS: 'GET_SUGGESTIONS_SUCCESS',
    GET_SUGGESTIONS_FAILURE: 'GET_SUGGESTIONS_FAILURE',

    GET_SUGGESTIONS_BY_ARTICLE_REQUEST: 'GET_SUGGESTIONS_BY_ARTICLE_REQUEST',
    GET_SUGGESTIONS_BY_ARTICLE_SUCCESS: 'GET_SUGGESTIONS_BY_ARTICLE_SUCCESS',
    GET_SUGGESTIONS_BY_ARTICLE_FAILURE: 'GET_SUGGESTIONS_BY_ARTICLE_FAILURE',

    GET_SUGGESTIONS_BY_PARAGRAPH: 'GET_SUGGESTIONS_BY_PARAGRAPH',

    CREATE_SUGGESTION_REQUEST: 'CREATE_SUGGESTION_REQUEST',
    CREATE_SUGGESTION_SUCCESS: 'CREATE_SUGGESTION_SUCCESS',
    CREATE_SUGGESTION_FAILURE: 'CREATE_SUGGESTION_FAILURE',

    UPDATE_SUGGESTION_REQUEST: 'UPDATE_SUGGESTION_REQUEST',
    UPDATE_SUGGESTION_SUCCESS: 'UPDATE_SUGGESTION_SUCCESS',
    UPDATE_SUGGESTION_FAILURE: 'UPDATE_SUGGESTION_FAILURE',

    REMOVE_SUGGESTION_REQUEST: 'REMOVE_SUGGESTION_REQUEST',
    REMOVE_SUGGESTION_SUCCESS: 'REMOVE_SUGGESTION_SUCCESS',
    REMOVE_SUGGESTION_FAILURE: 'REMOVE_SUGGESTION_FAILURE',

    SET_SUGGESTION_FILTER: 'SET_SUGGESTION_FILTER'
};